"use client";
import { useState, useTransition } from "react";
import { createCostCentre, createExpenseHead, createSalesman, linkPartyToCompany } from "@/lib/actions/masters";
import { Button, Input, Select } from "@/components/ui/primitives";
type Company={id:string;code:string;name:string}; type Party={id:string;code:string;name:string}; type Ledger={id:string;company_id:string;party_id:string|null;code:string;name:string}; type Group={id:string;code:string;name:string};
function Result({error,message}:{error:string|null;message:string|null}){return <>{error?<p className="text-sm text-[var(--danger)]">{error}</p>:null}{message?<p className="text-sm text-[var(--accent)]">{message}</p>:null}</>}
export function DimensionForms({companies,parties,ledgers,groups}:{companies:Company[];parties:Party[];ledgers:Ledger[];groups:Group[]}){const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[pending,startTransition]=useTransition();const run=(fn:()=>Promise<{ok:boolean;error?:string}>,success:string)=>startTransition(async()=>{setError(null);setMessage(null);const r=await fn();if(!r.ok)setError(r.error??"Failed");else setMessage(success)});return <div className="grid gap-4 xl:grid-cols-2">
<form className="grid gap-3 rounded-lg border p-4 md:grid-cols-2" action={(fd)=>run(()=>linkPartyToCompany({partyId:String(fd.get("partyId")),companyId:String(fd.get("companyId")),ledgerId:String(fd.get("ledgerId")),creditLimit:fd.get("creditLimit")?Number(fd.get("creditLimit")):undefined}),"Party linked")}><h3 className="font-semibold md:col-span-2">Party → company ledger</h3><Select label="Party" name="partyId" required><option value="">Select</option>{parties.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</Select><Select label="Company" name="companyId" required><option value="">Select</option>{companies.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</Select><Select label="Party ledger" name="ledgerId" required><option value="">Select</option>{ledgers.filter(l=>l.party_id).map(l=><option key={l.id} value={l.id}>{l.code} — {l.name}</option>)}</Select><Input label="Credit limit" name="creditLimit" type="number" min="0" step="0.0001"/><Button type="submit" disabled={pending}>Save link</Button></form>
<form className="grid gap-3 rounded-lg border p-4 md:grid-cols-2" action={(fd)=>run(()=>createCostCentre({companyId:String(fd.get("companyId")),code:String(fd.get("code")),name:String(fd.get("name"))}),"Cost centre created")}><h3 className="font-semibold md:col-span-2">Cost centre</h3><Select label="Company" name="companyId" required><option value="">Select</option>{companies.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</Select><Input label="Code" name="code" required/><Input label="Name" name="name" required/><Button type="submit" disabled={pending}>Create</Button></form>
<form className="grid gap-3 rounded-lg border p-4 md:grid-cols-2" action={(fd)=>run(()=>createSalesman({groupId:String(fd.get("groupId")),partyId:String(fd.get("partyId")||"")||undefined,code:String(fd.get("code")),name:String(fd.get("name")),roleType:String(fd.get("roleType")) as "salesman"|"broker",commissionPct:Number(fd.get("commissionPct")||0)}),"Salesman/broker created")}><h3 className="font-semibold md:col-span-2">Salesman / broker</h3><Select label="Group" name="groupId" required><option value="">Select</option>{groups.map(g=><option key={g.id} value={g.id}>{g.code} — {g.name}</option>)}</Select><Select label="Role" name="roleType"><option value="salesman">Salesman</option><option value="broker">Broker</option></Select><Input label="Code" name="code" required/><Input label="Name" name="name" required/><Select label="Linked party (optional)" name="partyId"><option value="">None</option>{parties.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</Select><Input label="Commission %" name="commissionPct" type="number" min="0" max="100" step="0.0001" defaultValue="0"/><Button type="submit" disabled={pending}>Create</Button></form>
<form className="grid gap-3 rounded-lg border p-4 md:grid-cols-2" action={(fd)=>run(()=>createExpenseHead({companyId:String(fd.get("companyId")),ledgerId:String(fd.get("ledgerId")),code:String(fd.get("code")),name:String(fd.get("name"))}),"Expense head created")}><h3 className="font-semibold md:col-span-2">Expense head</h3><Select label="Company" name="companyId" required><option value="">Select</option>{companies.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</Select><Select label="Expense ledger" name="ledgerId" required><option value="">Select</option>{ledgers.map(l=><option key={l.id} value={l.id}>{l.code} — {l.name}</option>)}</Select><Input label="Code" name="code" required/><Input label="Name" name="name" required/><Button type="submit" disabled={pending}>Create</Button></form><div className="xl:col-span-2"><Result error={error} message={message}/></div></div>}
