"use client";

import { useMemo, useState, useTransition } from "react";
import { allocateBillSettlement, createBusinessDocument } from "@/lib/actions/business-documents";
import { FinancialYearSelect } from "@/components/masters/financial-year-select";
import { Button, Input, Select } from "@/components/ui/primitives";
import { removeAccountingAttachment, uploadAccountingAttachment } from "@/lib/attachments";

type Item = { description: string; hsnSac: string; quantity: string; unit: string; rate: string; discountAmount: string; gstRate: string; tradeLedgerId: string; costCentreId: string; salesmanId: string };
type Ledger = { id: string; company_id: string; code: string; name: string; ledger_type: string; party_id: string | null };
export function BusinessDocumentForm({ companies, years, parties, ledgers, costCentres, salesmen, lockType }: { companies: Array<{id:string;code:string;name:string}>; years: Array<{id:string;company_id:string;code:string}>; parties: Array<{id:string;code:string;name:string}>; ledgers: Ledger[]; costCentres: Array<{id:string;company_id:string;code:string;name:string}>; salesmen: Array<{id:string;code:string;name:string;role_type:string}>; lockType?: "sale" | "purchase" }) {
  const emptyItem: Item = {description:"",hsnSac:"",quantity:"1",unit:"NOS",rate:"",discountAmount:"0",gstRate:"0",tradeLedgerId:"",costCentreId:"",salesmanId:""};
  const [companyId,setCompanyId]=useState(""); const [partyId,setPartyId]=useState(""); const [items,setItems]=useState<Item[]>([emptyItem]); const [attachment,setAttachment]=useState<File|null>(null); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const [pending,startTransition]=useTransition();
  const companyLedgers=useMemo(()=>ledgers.filter((l)=>l.company_id===companyId),[ledgers,companyId]); const partyLedgers=companyLedgers.filter((l)=>l.party_id===partyId); const update=(index:number,key:keyof Item,value:string)=>setItems((current)=>current.map((item,i)=>i===index?{...item,[key]:value}:item));
  return <form className="space-y-4 rounded-lg border border-[var(--border)] bg-[var(--surface)] p-4" action={(fd)=>startTransition(async()=>{setError(null);setMessage(null);let uploaded;try{if(attachment)uploaded=await uploadAccountingAttachment(companyId,attachment);}catch(cause){setError(cause instanceof Error?cause.message:"Could not upload attachment");return;}const result=await createBusinessDocument({companyId,financialYearId:String(fd.get("financialYearId")),documentType:String(fd.get("documentType")) as "sale"|"purchase",documentNumber:String(fd.get("documentNumber")),documentDate:String(fd.get("documentDate")),dueDate:String(fd.get("dueDate")),partyId,partyLedgerId:String(fd.get("partyLedgerId")),placeOfSupply:String(fd.get("placeOfSupply")||"")||undefined,isInterstate:fd.get("isInterstate")==="on",cgstLedgerId:String(fd.get("cgstLedgerId")||"")||undefined,sgstLedgerId:String(fd.get("sgstLedgerId")||"")||undefined,igstLedgerId:String(fd.get("igstLedgerId")||"")||undefined,tdsLedgerId:String(fd.get("tdsLedgerId")||"")||undefined,roundOffLedgerId:String(fd.get("roundOffLedgerId")||"")||undefined,tdsSection:String(fd.get("tdsSection")||"")||undefined,tdsRate:String(fd.get("tdsRate")||"0")||"0",roundOff:String(fd.get("roundOff")||"0")||"0",ewayBillNo:String(fd.get("ewayBillNo")||"")||undefined,narration:String(fd.get("narration")||"")||undefined,attachment:uploaded,items:items.map((item)=>({description:item.description,hsnSac:item.hsnSac||undefined,quantity:item.quantity,unit:item.unit,rate:item.rate,discountAmount:item.discountAmount||"0",gstRate:item.gstRate||"0",tradeLedgerId:item.tradeLedgerId,costCentreId:item.costCentreId||undefined,salesmanId:item.salesmanId||undefined}))});if(!result.ok){if(uploaded)await removeAccountingAttachment(uploaded.storagePath);setError(result.error);return;}setMessage(`Invoice saved as draft ${result.data.id}`);})}>
    <div className="grid gap-3 md:grid-cols-4"><Select label="Company" required value={companyId} onChange={(e)=>{setCompanyId(e.target.value);setPartyId("");}}><option value="">Select</option>{companies.map((c)=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</Select>{lockType ? <input type="hidden" name="documentType" value={lockType} /> : <Select label="Type" name="documentType" required><option value="sale">Sale invoice</option><option value="purchase">Purchase invoice</option></Select>}<FinancialYearSelect companyId={companyId} years={years} name="financialYearId" required /><Input label="Invoice number" name="documentNumber" required/><Input label="Invoice date" name="documentDate" type="date" required/><Input label="Due date" name="dueDate" type="date" required/><Select label="Party" required value={partyId} onChange={(e)=>setPartyId(e.target.value)}><option value="">Select</option>{parties.map((p)=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</Select><Select label="Party ledger" name="partyLedgerId" required disabled={!partyId}><option value="">Select</option>{partyLedgers.map((l)=><option key={l.id} value={l.id}>{l.code} — {l.name}</option>)}</Select></div>
    <h3 className="font-semibold">Items</h3>{items.map((item,index)=><div key={index} className="grid gap-2 rounded border border-[var(--border)] p-3 md:grid-cols-4"><Input label="Description" required value={item.description} onChange={(e)=>update(index,"description",e.target.value)}/><Input label="HSN/SAC" value={item.hsnSac} onChange={(e)=>update(index,"hsnSac",e.target.value)}/><Input label="Quantity" type="number" min="0.0001" step="0.0001" required value={item.quantity} onChange={(e)=>update(index,"quantity",e.target.value)}/><Input label="Unit" required value={item.unit} onChange={(e)=>update(index,"unit",e.target.value)}/><Input label="Rate" type="number" min="0" step="0.0001" required value={item.rate} onChange={(e)=>update(index,"rate",e.target.value)}/><Input label="Discount" type="number" min="0" step="0.0001" value={item.discountAmount} onChange={(e)=>update(index,"discountAmount",e.target.value)}/><Input label="GST %" type="number" min="0" max="100" step="0.0001" value={item.gstRate} onChange={(e)=>update(index,"gstRate",e.target.value)}/><Select label="Sales / purchase ledger" required value={item.tradeLedgerId} onChange={(e)=>update(index,"tradeLedgerId",e.target.value)}><option value="">Select</option>{companyLedgers.filter((l)=>l.ledger_type==="general").map((l)=><option key={l.id} value={l.id}>{l.code} — {l.name}</option>)}</Select><Select label="Cost centre" value={item.costCentreId} onChange={(e)=>update(index,"costCentreId",e.target.value)}><option value="">None</option>{costCentres.filter((c)=>c.company_id===companyId).map((c)=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</Select><Select label="Salesman / broker" value={item.salesmanId} onChange={(e)=>update(index,"salesmanId",e.target.value)}><option value="">None</option>{salesmen.map((s)=><option key={s.id} value={s.id}>{s.code} — {s.name} ({s.role_type})</option>)}</Select><Button type="button" variant="ghost" disabled={items.length===1} onClick={()=>setItems((current)=>current.filter((_,i)=>i!==index))}>Remove item</Button></div>)}
    <Button type="button" variant="secondary" onClick={()=>setItems((current)=>[...current,{...emptyItem}])}>Add item</Button>
    <div className="grid gap-3 md:grid-cols-4"><Input label="Place of supply (state code)" name="placeOfSupply" maxLength={2}/><label className="flex items-center gap-2 self-end py-2 text-sm"><input type="checkbox" name="isInterstate"/>Inter-state (IGST)</label><Select label="CGST ledger" name="cgstLedgerId"><option value="">None</option>{companyLedgers.map((l)=><option key={l.id} value={l.id}>{l.code} — {l.name}</option>)}</Select><Select label="SGST ledger" name="sgstLedgerId"><option value="">None</option>{companyLedgers.map((l)=><option key={l.id} value={l.id}>{l.code} — {l.name}</option>)}</Select><Select label="IGST ledger" name="igstLedgerId"><option value="">None</option>{companyLedgers.map((l)=><option key={l.id} value={l.id}>{l.code} — {l.name}</option>)}</Select><Select label="TDS ledger" name="tdsLedgerId"><option value="">None</option>{companyLedgers.map((l)=><option key={l.id} value={l.id}>{l.code} — {l.name}</option>)}</Select><Input label="TDS section" name="tdsSection"/><Input label="TDS %" name="tdsRate" type="number" min="0" max="100" step="0.0001" defaultValue="0"/><Input label="Round-off" name="roundOff" type="number" min="-10" max="10" step="0.0001" defaultValue="0"/><Select label="Round-off ledger" name="roundOffLedgerId"><option value="">None</option>{companyLedgers.map((l)=><option key={l.id} value={l.id}>{l.code} — {l.name}</option>)}</Select><Input label="E-way bill no." name="ewayBillNo"/><Input label="Narration" name="narration"/><label className="block space-y-1.5 text-sm"><span className="font-medium">Supporting document</span><input type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" className="block w-full" onChange={(event)=>setAttachment(event.target.files?.[0]??null)}/></label></div>
    {error?<p className="text-sm text-[var(--danger)]">{error}</p>:null}{message?<p className="text-sm text-[var(--accent)]">{message}</p>:null}<Button type="submit" disabled={pending}>Save invoice draft</Button>
  </form>;
}

export function BillAllocationForm({ documentId, outstanding, settlementLines }: { documentId:string; outstanding:number; settlementLines:Array<{id:string;label:string}> }) { const [error,setError]=useState<string|null>(null); const [pending,startTransition]=useTransition(); return <form className="flex min-w-[520px] gap-2" action={(fd)=>startTransition(async()=>{setError(null);const result=await allocateBillSettlement({documentId,settlementVoucherLineId:String(fd.get("lineId")),amount:String(fd.get("amount")||""),allocationDate:String(fd.get("date"))});if(!result.ok)setError(result.error);})}><select name="lineId" required className="rounded border px-2"><option value="">Receipt/payment</option>{settlementLines.map((line)=><option key={line.id} value={line.id}>{line.label}</option>)}</select><input name="amount" type="number" max={outstanding} step="0.0001" required placeholder="Amount" className="w-28 rounded border px-2"/><input name="date" type="date" required className="rounded border px-2"/><Button type="submit" disabled={pending||outstanding<=0}>Allocate</Button>{error?<span className="text-xs text-[var(--danger)]">{error}</span>:null}</form>; }
